-- Catherine's ready-to-publish five-lesson collection.

insert into public.teacher_dna (teacher_id, personality, teaching_style, stories, memories, values, course_world)
values ('67bb132f-a70a-4bfb-8f08-9ec6fdd00349','Literary, reflective, curious, gentle, and never patronising.','Story-led, gradual scaffolding, Socratic questions, and child-friendly critical thinking.','Uses stories to help children notice language, perspective, emotion, and culture.','','Careful expression, empathy, ambiguity, evidence, and independent thought.','Letter World')
on conflict (teacher_id) do update set personality=excluded.personality, teaching_style=excluded.teaching_style, stories=excluded.stories, values=excluded.values, course_world=excluded.course_world, updated_at=now();

insert into public.course_collections (id,teacher_id,title,description,language,age_range,world,story_question,human_moment_policy,status,teacher_dna_snapshot)
values ('c1000000-0000-4000-8000-000000000001','67bb132f-a70a-4bfb-8f08-9ec6fdd00349','Letter World: Letters, Love & Little Poems','Five connected English story lessons with Catherine. Read a gentle original story, notice feelings, and write a kind letter of your own.','English','6–12','Letter World','What can a letter say that feels hard to say aloud?','When a child shares a heavy feeling, Catherine pauses gently and encourages a trusted grown-up. Parent-approved support can notify the family and educator without sharing the child’s words.','published','{"personality":"Literary, reflective, curious, gentle, and never patronising.","teaching_style":"Story-led, gradual scaffolding, Socratic questions, and child-friendly critical thinking.","stories":"Uses stories to help children notice language, perspective, emotion, and culture.","values":"Careful expression, empathy, ambiguity, evidence, and independent thought.","course_world":"Letter World"}'::jsonb)
on conflict (id) do update set title=excluded.title,description=excluded.description,status='published',teacher_dna_snapshot=excluded.teacher_dna_snapshot,updated_at=now();

update public.courses set title='A Quiet Farewell',description='Lesson 1 of Letter World: name feelings around goodbye, confusion, sadness, and care.',language='English' where id='f15af2ba-b75e-4440-9a63-b5514d031aa9';
insert into public.courses (id,teacher_id,title,description,language) values
('c1010000-0000-4000-8000-000000000002','67bb132f-a70a-4bfb-8f08-9ec6fdd00349','A New Beginning','Lesson 2 of Letter World: enter the Letter House and learn warm beginnings.','English'),
('c1010000-0000-4000-8000-000000000003','67bb132f-a70a-4bfb-8f08-9ec6fdd00349','Other People’s Hearts','Lesson 3 of Letter World: notice care hidden in small everyday actions.','English'),
('c1010000-0000-4000-8000-000000000004','67bb132f-a70a-4bfb-8f08-9ec6fdd00349','A Letter for Everyone','Lesson 4 of Letter World: explore kindness, gratitude, and hope.','English'),
('c1010000-0000-4000-8000-000000000005','67bb132f-a70a-4bfb-8f08-9ec6fdd00349','Your Letter','Lesson 5 of Letter World: write one true and kind letter.','English')
on conflict (id) do update set title=excluded.title,description=excluded.description,language=excluded.language;

insert into public.collection_lessons (collection_id,course_id,position) values
('c1000000-0000-4000-8000-000000000001','f15af2ba-b75e-4440-9a63-b5514d031aa9',1),
('c1000000-0000-4000-8000-000000000001','c1010000-0000-4000-8000-000000000002',2),
('c1000000-0000-4000-8000-000000000001','c1010000-0000-4000-8000-000000000003',3),
('c1000000-0000-4000-8000-000000000001','c1010000-0000-4000-8000-000000000004',4),
('c1000000-0000-4000-8000-000000000001','c1010000-0000-4000-8000-000000000005',5)
on conflict (collection_id,course_id) do update set position=excluded.position;

insert into public.course_lesson_content (course_id,story_beat,learning_objectives,vocabulary,mentor_context,human_moment_rules,lesson_steps) values
('f15af2ba-b75e-4440-9a63-b5514d031aa9','Elia hears a caring phrase she cannot name yet.',ARRAY['Name feelings around goodbye','Use farewell and care in a sentence'],'["farewell","confused","sad","care"]'::jsonb,'Catherine tells the opening slowly, invites multiple possible feelings, and never forces a child to share a personal loss.','["Thank a child for sharing a heavy feeling.","Invite a trusted grown-up; do not ask for private details."]'::jsonb,jsonb_build_array(jsonb_build_object('t','intro','title','A Quiet Farewell','sub','Letter World · Lesson 1 of 5','say','Hello, little letter keeper. In Letter World, Elia hears a caring phrase she does not understand. We can be curious about feelings without needing every answer today.','scene','night city stars','costume','storyteller'),jsonb_build_object('t','card','word','farewell','emoji','💌','action','Place a hand on your heart and wave gently.','move',true,'say','Farewell means goodbye. A farewell can feel sad, confusing, or quiet. Say it softly: farewell.','scene','night city stars','costume','storyteller'),jsonb_build_object('t','move','emoji','✨','prompt','Write a tiny letter in the air.','say','Let us make a small, gentle letter in the air.','scene','night sky moon','costume','wizard'),jsonb_build_object('t','quiz','question','Which word means a gentle goodbye?','say','Which word did we learn for a gentle goodbye?','options',jsonb_build_array(jsonb_build_object('label','farewell','correct',true),jsonb_build_object('label','volcano','correct',false),jsonb_build_object('label','rocket','correct',false)),'scene','night sky moon','costume','wizard'),jsonb_build_object('t','finale','say','You listened with great care. Next time, Elia enters the Letter House.','scene','night sky stars','costume','storyteller'))),
('c1010000-0000-4000-8000-000000000002','Elia enters the Letter House and learns that shy words can travel on paper.',ARRAY['Use a letter greeting','Understand Dear and gentle'],'["Dear","letter","pen","gentle"]'::jsonb,'Catherine makes letter structure concrete through imagination and one small sentence at a time.','["Normalize uncertainty.","Encourage children to choose a safe recipient."]'::jsonb,jsonb_build_array(jsonb_build_object('t','intro','title','A New Beginning','sub','Letter World · Lesson 2 of 5','say','Welcome back. Elia has arrived at the Letter House, where words can travel farther than our voices.','scene','sunny city','costume','storyteller'),jsonb_build_object('t','card','word','Dear …,','emoji','✉️','action','Pretend to open a letter slowly.','move',false,'say','Many kind letters begin with Dear, then a name. Say: Dear Grandma.','scene','sunny city','costume','storyteller'),jsonb_build_object('t','move','emoji','🪶','prompt','Touch an imaginary feather softly.','say','Gentle means soft and careful. Let us write gentle words.','scene','forest sunlight','costume','ranger'),jsonb_build_object('t','quiz','question','Which beginning belongs at the top of a kind letter?','say','Choose the warm beginning.','options',jsonb_build_array(jsonb_build_object('label','Dear Grandma,','correct',true),jsonb_build_object('label','Jump high!','correct',false),jsonb_build_object('label','Blue umbrella','correct',false)),'scene','sunny city','costume','storyteller'),jsonb_build_object('t','finale','say','You have the first part of a letter. Next we notice hidden care in everyday words.','scene','night sky stars','costume','storyteller'))),
('c1010000-0000-4000-8000-000000000003','Elia notices that small acts can carry large feelings.',ARRAY['Share a concrete memory','Name warmth and gratitude'],'["I remember","thank you","warm","miss"]'::jsonb,'Catherine uses sensory, specific prompts rather than asking children for big disclosures.','["Let children pass on personal questions.","Offer pet, tree, or future-self alternatives."]'::jsonb,jsonb_build_array(jsonb_build_object('t','intro','title','Other People’s Hearts','sub','Letter World · Lesson 3 of 5','say','Today Elia learns that care can hide inside a saved snack, a warm coat, or someone remembering your favourite story.','scene','forest sunlight','costume','ranger'),jsonb_build_object('t','card','word','I remember …','emoji','🌿','action','Tap your temple, then smile at a small memory.','move',true,'say','To share one true moment, we can say: I remember when you helped me.','scene','forest sunlight','costume','ranger'),jsonb_build_object('t','move','emoji','🧡','prompt','Place warm hands over your heart.','say','Warm can be a feeling inside when someone listens or remembers you.','scene','night forest fireflies','costume','wizard'),jsonb_build_object('t','quiz','question','Which sentence shares a small memory?','say','Listen for the true little memory.','options',jsonb_build_array(jsonb_build_object('label','I remember when you read with me.','correct',true),jsonb_build_object('label','Purple is a square.','correct',false),jsonb_build_object('label','Seven clouds jump.','correct',false)),'scene','night forest fireflies','costume','wizard'),jsonb_build_object('t','finale','say','Small memories can become brave sentences. Next, Elia writes kindness for more than one person.','scene','night sky stars','costume','wizard'))),
('c1010000-0000-4000-8000-000000000004','Elia learns that care can be family, friendship, gratitude, and hope.',ARRAY['Use a kind closing','Define care in personal words'],'["With love","kind","grateful","I hope"]'::jsonb,'Catherine invites critical thinking: care may look different across people and cultures.','["Do not frame love romantically.","Accept multiple answers and uncertainty."]'::jsonb,jsonb_build_array(jsonb_build_object('t','intro','title','A Letter for Everyone','sub','Letter World · Lesson 4 of 5','say','Elia sees that kindness can be a friend waiting beside you, a family member checking in, or a stranger being thoughtful.','scene','castle sunset stars','costume','storyteller'),jsonb_build_object('t','card','word','With love,','emoji','🌸','action','Draw a small flower in the air and sign your name.','move',false,'say','A letter can end with With love, and then your name. Say: With love, Catherine.','scene','castle sunset stars','costume','storyteller'),jsonb_build_object('t','move','emoji','⭐','prompt','Make a tiny thankful bow.','say','Grateful means thankful for something meaningful. You may pass if you want.','scene','night sky moon','costume','wizard'),jsonb_build_object('t','quiz','question','What can a kind letter include?','say','Choose the answer that carries care.','options',jsonb_build_array(jsonb_build_object('label','A thankful wish','correct',true),jsonb_build_object('label','A secret password','correct',false),jsonb_build_object('label','A racing score','correct',false)),'scene','night sky moon','costume','wizard'),jsonb_build_object('t','finale','say','You have gathered gentle words for a letter. The last page belongs to you.','scene','night sky stars','costume','storyteller'))),
('c1010000-0000-4000-8000-000000000005','The child becomes a letter keeper and writes one short true message.',ARRAY['Use a three-part letter scaffold','Create without fear of mistakes'],'["Dear","I remember","I felt","I hope"]'::jsonb,'Catherine gives a beginner-friendly sandwich structure, then lets the child choose writing, drawing, or voice.','["Never grade feelings.","If a child shares distress, pause the activity and encourage a trusted grown-up."]'::jsonb,jsonb_build_array(jsonb_build_object('t','intro','title','Your Letter','sub','Letter World · Lesson 5 of 5','say','Now you are a letter keeper. Your letter can be for a family member, friend, pet, tree, or future you. It only needs to be true.','scene','sunny city','costume','storyteller'),jsonb_build_object('t','card','word','I hope you …','emoji','💫','action','Make a small wish on your open palm.','move',false,'say','A kind letter can end with a wish. Say: I hope you have a lovely day.','scene','sunny city','costume','storyteller'),jsonb_build_object('t','move','emoji','🕊️','prompt','Fold an invisible letter and send it gently into the sky.','say','Fold your invisible letter, press it closed, and send it safely. Your words can be brave and soft together.','scene','night sky moon','costume','wizard'),jsonb_build_object('t','quiz','question','What matters most in a kind letter?','say','One last question.','options',jsonb_build_array(jsonb_build_object('label','A true and kind thought','correct',true),jsonb_build_object('label','Perfect spelling','correct',false),jsonb_build_object('label','The longest letter','correct',false)),'scene','night sky moon','costume','wizard'),jsonb_build_object('t','finale','say','You have written the first line of your own Letter World story. One day, you will understand love a little more — starting with one kind sentence. I am proud of you.','scene','night sky stars','costume','storyteller')))
on conflict (course_id) do update set story_beat=excluded.story_beat,learning_objectives=excluded.learning_objectives,vocabulary=excluded.vocabulary,mentor_context=excluded.mentor_context,human_moment_rules=excluded.human_moment_rules,lesson_steps=excluded.lesson_steps,updated_at=now();
